50 Numpy Functions


In [2]:
import numpy as np

In [3]:
#function 1 
a1= np.arange(28)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [4]:
#function 2
a2= a1.reshape(2,2,7)
a2

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27]]])

In [5]:
#function 3
a1.dtype

dtype('int32')

In [6]:
#function 4
a1.shape

(28,)

In [78]:
#function 5
np.hsplit(a2,1)

[array([[[ 0,  1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12, 13]],
 
        [[14, 15, 16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25, 26, 27]]])]

In [39]:
#function 6
len(a1)

28

In [59]:
#function 7
a1.min()

0

In [71]:
#function 8
a1[9]

9

In [74]:
#function 9
a2[1,0,3]

17

In [75]:
#function 10
a1[3:21]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [7]:
#function 11
a2.size

28

In [23]:
#function 12
b=a2.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [24]:
#function 13
np.add(a1,b)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54])

In [25]:
#function 14
np.subtract(a1,b)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [8]:
#function 15
a3=np.array([(1,2,3),(8,9,10)])
a3

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [76]:
#function 16
np.transpose(a3)

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10]])

In [27]:
#function 17
np.sin(a3)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.98935825,  0.41211849, -0.54402111]])

In [28]:
#function 18
np.cos(a3)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.14550003, -0.91113026, -0.83907153]])

In [29]:
#function 19
np.tan(a3)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [-6.79971146, -0.45231566,  0.64836083]])

In [30]:
#function 20
np.log(a3)

array([[0.        , 0.69314718, 1.09861229],
       [2.07944154, 2.19722458, 2.30258509]])

In [31]:
#function 21
np.sqrt(a3)

array([[1.        , 1.41421356, 1.73205081],
       [2.82842712, 3.        , 3.16227766]])

In [42]:
#function 22
np.exp(a3)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04]])

In [32]:
#function 23
np.zeros(4)


array([0., 0., 0., 0.])

In [46]:
#function 24
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
#function 25
c=np.ones((2,3))


In [41]:
#function 26
c.astype(int)

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
#function 27
c.sum()

6.0

In [52]:
#function 28
c.mean()

1.0

In [54]:
#function 29
np.std(c)

0.0

In [56]:
#function 30
h=c.view()
h

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
#function 31
f=c.copy()
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
#function 32
y=np.full((3,3),5)
y

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [48]:
#function 33
np.multiply(x,y)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [49]:
#function 34
np.divide(x,y)

array([[0.2, 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0.2]])

In [36]:
#function 35
np.linspace(0,20,5)


array([ 0.,  5., 10., 15., 20.])

In [37]:
#function 36
np.copy(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [82]:
#function 37
np.empty((2,4),int)


array([[         0, 1075052544,          0, 1076101120],
       [         0, 1076756480,          0, 1077149696]])

In [83]:
#function 38
np.array_equal(a1,b)

True

In [84]:
#function 39
x==y

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [85]:
#function 40
a3>5

array([[False, False, False],
       [ True,  True,  True]])

In [86]:
#function 41
np.append(b,35)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 35])

In [87]:
#function 42
np.insert(b,5,40)

array([ 0,  1,  2,  3,  4, 40,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [88]:
#function 43
np.delete(b,9,axis=0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [89]:
#function 44
np.split(b,4)

[array([0, 1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27])]

In [93]:
#function 45
np.concatenate((a1,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27])

In [94]:
#function 46
np.power(a3,2)

array([[  1,   4,   9],
       [ 64,  81, 100]], dtype=int32)

In [95]:
p=np.array([1.5,-6.9,7.2])

In [96]:
#function 47
np.abs(p)

array([1.5, 6.9, 7.2])

In [97]:
#function 48
np.round(p)

array([2., 7., 7.])

In [98]:
#function 49
np.ceil(p)

array([2., 7., 8.])

In [99]:
#function 50
np.floor(p)

array([1., 6., 7.])